services:

  database:
    image: postgres:latest
    container_name: cdc-aggregator-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
